import React, { useState } from "react";
import { ResearchReport } from "../types";
import { Download, Copy, Check, FileText, Code, Share2, BookOpen, X } from "lucide-react";

interface CitationsExportModalProps {
  report: ResearchReport;
  onClose: () => void;
}

export const CitationsExportModal: React.FC<CitationsExportModalProps> = ({
  report,
  onClose,
}) => {
  const [activeTab, setActiveTab] = useState<"citations" | "export">("citations");
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  const copyToClipboard = (text: string, format: string) => {
    navigator.clipboard.writeText(text);
    setCopiedFormat(format);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportMarkdown = () => {
    const md = `# ${report.title}
*Generated by SoftRoy AI Multi-Agent Academic Research Assistant*
*Date: ${new Date(report.createdAt).toLocaleDateString()}*

## Executive Summary
${report.executiveSummary}

## Detailed Analysis
${report.detailedAnalysis}

## Scientific Review
- Methodology Score: ${report.scientificReview.methodologyScore}%
- Statistical Validity: ${report.scientificReview.statisticalValidity}%
- Claim Grounding: ${report.scientificReview.claimGroundingScore}%
- Overall Confidence Score: ${report.confidenceScore}%

## Evidence Table
${report.evidenceTable.map((e) => `- **Claim:** ${e.claim}\n  - **Source:** ${e.sourcePaper}\n  - **Snippet:** "${e.evidenceText}"\n  - **Status:** ${e.status}`).join("\n")}

## Citations
### BibTeX
\`\`\`bibtex
${report.citations.bibtex}
\`\`\`

### APA Format
${report.citations.apa}

### IEEE Format
${report.citations.ieee}
`;
    downloadFile(md, `${report.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}.md`, "text/markdown");
  };

  const exportHTML = () => {
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${report.title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1e293b; }
    h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
    h2 { color: #1e293b; margin-top: 30px; }
    .box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; margin: 15px 0; }
    code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <p><em>SoftRoy AI Academic Report • ${new Date(report.createdAt).toLocaleDateString()}</em></p>

  <h2>Executive Summary</h2>
  <div class="box">${report.executiveSummary}</div>

  <h2>Detailed Analysis</h2>
  <div>${report.detailedAnalysis.replace(/\n/g, "<br>")}</div>

  <h2>BibTeX Citation</h2>
  <pre class="box"><code>${report.citations.bibtex}</code></pre>
</body>
</html>`;
    downloadFile(html, `${report.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}.html`, "text/html");
  };

  return (
    <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs z-50 flex items-center justify-center p-4">
      <div className="bg-white border border-slate-200 rounded-2xl w-full max-w-2xl overflow-hidden shadow-xl flex flex-col max-h-[85vh]">
        {/* Modal Header */}
        <div className="p-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-indigo-600" />
            <h3 className="font-bold text-slate-900 text-sm">Citations & Report Export Hub</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Toggle */}
        <div className="flex border-b border-slate-200 bg-slate-50/50 px-4">
          <button
            onClick={() => setActiveTab("citations")}
            className={`py-2.5 px-4 text-xs font-semibold border-b-2 transition-colors ${
              activeTab === "citations"
                ? "border-indigo-600 text-indigo-700"
                : "border-transparent text-slate-500 hover:text-slate-800"
            }`}
          >
            Formatted Citations (BibTeX / APA / IEEE)
          </button>
          <button
            onClick={() => setActiveTab("export")}
            className={`py-2.5 px-4 text-xs font-semibold border-b-2 transition-colors ${
              activeTab === "export"
                ? "border-indigo-600 text-indigo-700"
                : "border-transparent text-slate-500 hover:text-slate-800"
            }`}
          >
            Export Full Report (Markdown / HTML / JSON)
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-5 overflow-y-auto space-y-4 bg-white">
          {activeTab === "citations" ? (
            <div className="space-y-4">
              {/* BibTeX */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-bold text-slate-800">BibTeX Citation</span>
                  <button
                    onClick={() => copyToClipboard(report.citations.bibtex, "bibtex")}
                    className="text-xs text-indigo-600 hover:text-indigo-800 font-semibold flex items-center gap-1"
                  >
                    {copiedFormat === "bibtex" ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedFormat === "bibtex" ? "Copied" : "Copy BibTeX"}
                  </button>
                </div>
                <pre className="text-xs text-indigo-900 font-mono bg-slate-50 p-3 rounded-lg border border-slate-200 overflow-x-auto">
                  {report.citations.bibtex}
                </pre>
              </div>

              {/* APA */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-bold text-slate-800">APA Format</span>
                  <button
                    onClick={() => copyToClipboard(report.citations.apa, "apa")}
                    className="text-xs text-indigo-600 hover:text-indigo-800 font-semibold flex items-center gap-1"
                  >
                    {copiedFormat === "apa" ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedFormat === "apa" ? "Copied" : "Copy APA"}
                  </button>
                </div>
                <div className="text-xs text-slate-800 bg-slate-50 p-3 rounded-lg border border-slate-200 font-medium">
                  {report.citations.apa}
                </div>
              </div>

              {/* IEEE */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-bold text-slate-800">IEEE Format</span>
                  <button
                    onClick={() => copyToClipboard(report.citations.ieee, "ieee")}
                    className="text-xs text-indigo-600 hover:text-indigo-800 font-semibold flex items-center gap-1"
                  >
                    {copiedFormat === "ieee" ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedFormat === "ieee" ? "Copied" : "Copy IEEE"}
                  </button>
                </div>
                <div className="text-xs text-slate-800 bg-slate-50 p-3 rounded-lg border border-slate-200 font-mono font-medium">
                  {report.citations.ieee}
                </div>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <button
                onClick={exportMarkdown}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200 hover:border-slate-300 hover:bg-slate-100 transition-all text-left shadow-2xs"
              >
                <div className="flex items-center gap-2 text-indigo-600 font-bold text-xs mb-1">
                  <FileText className="w-4 h-4" /> Export Markdown (.md)
                </div>
                <p className="text-xs text-slate-500">Complete structured research report in raw markdown format.</p>
              </button>

              <button
                onClick={exportHTML}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200 hover:border-slate-300 hover:bg-slate-100 transition-all text-left shadow-2xs"
              >
                <div className="flex items-center gap-2 text-emerald-700 font-bold text-xs mb-1">
                  <Code className="w-4 h-4" /> Export Standalone HTML (.html)
                </div>
                <p className="text-xs text-slate-500">Self-contained styled HTML file ready for distribution or printing.</p>
              </button>

              <button
                onClick={() => downloadFile(JSON.stringify(report, null, 2), `${report.id}.json`, "application/json")}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200 hover:border-slate-300 hover:bg-slate-100 transition-all text-left shadow-2xs"
              >
                <div className="flex items-center gap-2 text-purple-700 font-bold text-xs mb-1">
                  <Share2 className="w-4 h-4" /> Export Raw JSON Data (.json)
                </div>
                <p className="text-xs text-slate-500">Full structured object containing evidence nodes, graph, and metadata.</p>
              </button>

              <button
                onClick={() => copyToClipboard(report.executiveSummary, "summary")}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200 hover:border-slate-300 hover:bg-slate-100 transition-all text-left shadow-2xs"
              >
                <div className="flex items-center gap-2 text-amber-700 font-bold text-xs mb-1">
                  <Copy className="w-4 h-4" /> Copy Executive Summary
                </div>
                <p className="text-xs text-slate-500">Copy high-level summary directly to clipboard.</p>
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
