/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { Header } from "./components/Header";
import { Sidebar } from "./components/Sidebar";
import { ResearchInput } from "./components/ResearchInput";
import { AgentPipelineVisualizer } from "./components/AgentPipelineVisualizer";
import { ReportViewer } from "./components/ReportViewer";
import { Project, ResearchReport, ResearchMode, UploadedDocInfo } from "./types";
import { Sparkles, MessageSquare, Bot, User, FileText, ArrowRight, ShieldCheck, Cpu } from "lucide-react";

// Default pre-populated research report for instant working preview
const INITIAL_REPORT: ResearchReport = {
  id: "report-demo-1",
  title: "Deep Research: Test-Time Compute & Scalable Reasoning Models (2024–2026)",
  query: "Synthesize state-of-the-art breakthroughs in test-time compute scaling, tree search verification, and state space model architectures.",
  mode: "deep_research",
  createdAt: new Date().toISOString(),
  executiveSummary:
    "This multi-agent research synthesis evaluates recent paradigms in test-time compute allocation, process reward models (PRMs), and hybrid state-space transformer architectures. Analysis across arXiv, OpenAlex, and CrossRef literature confirms that allocating additional compute during inference via Monte Carlo Tree Search (MCTS) and self-consistency verification yields super-linear performance gains on complex mathematical reasoning and scientific code synthesis tasks.",
  detailedAnalysis: `### 1. Introduction & Research Landscape

In recent academic literature (2024–2026), a fundamental shift has occurred from pure pre-training scaling laws (Chinchilla) towards **Inference-Time Compute Scaling**. Rather than increasing parameter size indefinitely, modern architectures spend additional compute at test-time through iterative tree searches, self-correction loops, and verifier models.

### 2. Core Architectural Breakthroughs

#### A. Process Reward Models (PRMs) vs. Outcome Reward Models (ORMs)
* **Outcome Reward Models (ORMs)** evaluate only the final answer generated by the model.
* **Process Reward Models (PRMs)** evaluate each intermediate step of reasoning, drastically reducing error propagation in multi-step mathematical proofs and scientific problem solving.

#### B. Test-Time Search Strategies
1. **Best-of-N Sampling**: Sampling $N$ independent trajectories and ranking via PRMs.
2. **Monte Carlo Tree Search (MCTS)**: Dynamically expanding promising reasoning paths while pruning unviable branches.

### 3. Empirical Findings & Benchmarks

Cross-paper evaluation demonstrates that test-time search using a 7B parameter model guided by PRM verifiers can match or surpass a 70B parameter standard model on MATH-500 and HumanEval benchmarks.`,
  scientificReview: {
    methodologyScore: 94,
    statisticalValidity: 92,
    claimGroundingScore: 96,
    factVerificationScore: 95,
    missingEvidence: ["Long-term memory benchmarks on 1M+ token continuous contexts"],
    contradictions: ["Debate on compute efficiency trade-off between KV-cache memory vs PRM verifier latency"],
    confidenceScore: 95,
    summary:
      "Methodology passed multi-agent scientific review with high grounding confidence across peer-reviewed arXiv and OpenAlex citations.",
  },
  evidenceTable: [
    {
      claim: "Inference-time search with PRMs yields super-linear accuracy improvements on multi-step reasoning.",
      sourcePaper: "arXiv:2408.03314 (Scaling Laws for Inference-Time Compute)",
      evidenceText: "Applying MCTS search with a process verifier increases math accuracy by 28% without updating base model weights.",
      groundingScore: 96,
      status: "Verified",
    },
    {
      claim: "Process Reward Models reduce hallucination frequency compared to Outcome Reward Models.",
      sourcePaper: "OpenAlex:W43829102 (Step-Level Value Functions in LLMs)",
      evidenceText: "Step-wise reward modeling flags erroneous reasoning steps before compounding occurs in token generation.",
      groundingScore: 94,
      status: "Verified",
    },
    {
      claim: "State Space Models achieve linear $O(N)$ time complexity compared to Transformer $O(N^2)$ attention.",
      sourcePaper: "CrossRef:10.1145/mamba2024",
      evidenceText: "Selective state space layers maintain hidden state representations in constant memory during inference.",
      groundingScore: 92,
      status: "Verified",
    },
  ],
  timeline: [
    {
      year: 2023,
      title: "Introduction of Step-Level Value Verification",
      paperTitle: "Let's Verify Step by Step",
      authors: "Lightman et al.",
      significance: "Established PRM benchmarks proving process supervision outperforms outcome supervision.",
      category: "Milestone",
    },
    {
      year: 2024,
      title: "Inference-Time Compute Scaling Laws",
      paperTitle: "Scaling Test-Time Compute in Reasoning Models",
      authors: "Snell et al. (arXiv)",
      significance: "Proved test-time compute can trade off parameter size during inference.",
      category: "Methodology Breakthrough",
    },
    {
      year: 2025,
      title: "MCTS Integration in Open-Source LLMs",
      paperTitle: "Tree-Search Guided Code Synthesis",
      authors: "OpenAlex Academic Group",
      significance: "Demonstrated real-time Python execution feedback in tree-search nodes.",
      category: "Paradigm Shift",
    },
    {
      year: 2026,
      title: "Hybrid Mamba-Transformer Test-Time Engines",
      paperTitle: "SoftRoy AI Architectural Benchmark Report",
      authors: "SoftRoy Research Group",
      significance: "Combined linear memory state-space layers with test-time search verification.",
      category: "Milestone",
    },
  ],
  evidenceGraph: {
    nodes: [
      { id: "paper-1", label: "Snell et al. (2024)", type: "paper", details: "Inference-Time Scaling Laws paper on arXiv", qualityScore: 95 },
      { id: "claim-1", label: "Test-Time Search Boost", type: "claim", details: "PRMs enable 28% accuracy boost via MCTS search", qualityScore: 96 },
      { id: "method-1", label: "Monte Carlo Tree Search", type: "methodology", details: "MCTS expansion guided by process verifiers", qualityScore: 92 },
      { id: "result-1", label: "MATH-500 State of the Art", type: "result", details: "7B model matches 70B unguided baseline", qualityScore: 94 },
      { id: "dataset-1", label: "MATH-500 & HumanEval", type: "dataset", details: "Standard benchmark datasets for reasoning and code", qualityScore: 90 },
      { id: "gap-1", label: "KV-Cache Latency Overhead", type: "gap", details: "High memory bandwidth overhead during multi-path sampling", qualityScore: 85 },
    ],
    edges: [
      { source: "paper-1", target: "claim-1", relationship: "supports", confidence: 0.96 },
      { source: "method-1", target: "claim-1", relationship: "extends", confidence: 0.94 },
      { source: "claim-1", target: "result-1", relationship: "supports", confidence: 0.95 },
      { source: "method-1", target: "dataset-1", relationship: "uses_dataset", confidence: 0.92 },
      { source: "result-1", target: "gap-1", relationship: "identifies_gap", confidence: 0.88 },
    ],
  },
  paperComparisons: [
    {
      feature: "Search Strategy",
      paperA: "Best-of-N Independent Sampling",
      paperB: "Monte Carlo Tree Search (MCTS)",
      analysis: "MCTS allows branching and state reuse, reducing redundant token generation by 40%.",
      winner: "Paper B (MCTS)",
    },
    {
      feature: "Reward Signal",
      paperA: "Outcome Reward Model (ORM)",
      paperB: "Process Reward Model (PRM)",
      analysis: "PRMs evaluate step-wise correctness, catching hallucinated logic early in reasoning.",
      winner: "Paper B (PRM)",
    },
    {
      feature: "Memory Complexity",
      paperA: "Transformer Attention O(N²)",
      paperB: "Mamba State Space O(N)",
      analysis: "Mamba's linear memory allows longer search depth within fixed GPU VRAM limits.",
      winner: "Paper B (Mamba)",
    },
  ],
  limitations: [
    "High inference latency during multi-path search",
    "Requires trained verifiers specific to mathematical/coding domains",
  ],
  futureWork: [
    "Self-training PRMs through execution feedback without human step labels",
    "Quantized verifiers for on-device test-time search",
  ],
  mermaidDiagrams: [
    {
      id: "mermaid-1",
      title: "Test-Time Tree Search & Process Verification Workflow",
      description: "Layer 10 diagram generation depicting the 11-layer multi-agent verification pipeline",
      code: `flowchart TD
    A[User Academic Query] --> B[Layer 1 Intent & Query Optimizer]
    B --> C[Layer 4 Source Router: arXiv & OpenAlex]
    C --> D[Layer 5 Document Pipeline]
    D --> E[Layer 7 Evidence Graph Builder]
    E --> F[Layer 8 Scientific Review & PRM Verifier]
    F -->|Verified| G[Layer 10 Final Synthesis Report]
    F -->|Uncertain| C`,
    },
  ],
  sources: [
    {
      id: "arxiv-2408.03314",
      title: "Scaling Laws for Inference-Time Compute in Large Language Models",
      authors: ["Charlie Snell", "Jaehoon Lee", "Kelvin Xu", "Aviral Kumar"],
      year: 2024,
      venue: "arXiv Preprint",
      abstract: "We evaluate the relationship between pre-training compute and test-time search compute across reasoning benchmarks.",
      url: "https://arxiv.org/abs/2408.03314",
      source: "arXiv",
      citationsCount: 142,
      qualityScore: 96,
    },
    {
      id: "openalex-w43829102",
      title: "Let's Verify Step by Step: Process Supervision in Reasoning",
      authors: ["Hunter Lightman", "Vineet Kosaraju", "Yura Burda", "Harri Edwards"],
      year: 2023,
      venue: "OpenAlex Indexed Publication",
      abstract: "Process-supervised reward models train models to verify individual steps of reasoning.",
      url: "https://openalex.org/W43829102",
      source: "OpenAlex",
      citationsCount: 520,
      qualityScore: 98,
    },
  ],
  citations: {
    bibtex: `@article{snell2024inference,
  title={Scaling Laws for Inference-Time Compute in Large Language Models},
  author={Snell, Charlie and Lee, Jaehoon and Xu, Kelvin and Kumar, Aviral},
  journal={arXiv preprint arXiv:2408.03314},
  year={2024}
}`,
    apa: "Snell, C., Lee, J., Xu, K., & Kumar, A. (2024). Scaling Laws for Inference-Time Compute in Large Language Models. arXiv preprint arXiv:2408.03314.",
    ieee: 'C. Snell, J. Lee, K. Xu, and A. Kumar, "Scaling Laws for Inference-Time Compute in Large Language Models," arXiv preprint arXiv:2408.03314, 2024.',
  },
  confidenceScore: 95,
};

const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Quantum Computing & AI Models",
    description: "Multi-agent research project investigating test-time compute, LLMs, and quantum algorithms.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reports: [INITIAL_REPORT],
    bookmarks: [],
    uploadedFiles: [],
  },
];

export default function App() {
  const [projects, setProjects] = useState<Project[]>(INITIAL_PROJECTS);
  const [activeProject, setActiveProject] = useState<Project>(INITIAL_PROJECTS[0]);
  const [activeReport, setActiveReport] = useState<ResearchReport | null>(INITIAL_REPORT);
  const [isSidebarOpen, setIsSidebarOpen] = useState<boolean>(false);
  const [isExecuting, setIsExecuting] = useState<boolean>(false);
  const [currentLayer, setCurrentLayer] = useState<number>(0);

  // Handle running a new research query via Express backend
  const handleRunResearch = async (
    query: string,
    mode: ResearchMode,
    files: UploadedDocInfo[]
  ) => {
    try {
      setIsExecuting(true);
      setCurrentLayer(1);

      // Simulate step-by-step layer activation visual trace
      const interval = setInterval(() => {
        setCurrentLayer((prev) => {
          if (prev >= 11) {
            clearInterval(interval);
            return 11;
          }
          return prev + 1;
        });
      }, 350);

      const response = await fetch("/api/research/query", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, mode, uploadedFiles: files }),
      });

      clearInterval(interval);
      setCurrentLayer(11);

      const data = await response.json();

      if (data.success && data.report) {
        const newReport: ResearchReport = data.report;
        setActiveReport(newReport);

        // Save report into active project
        setProjects((prevProjects) =>
          prevProjects.map((p) =>
            p.id === activeProject.id
              ? { ...p, reports: [newReport, ...p.reports], updatedAt: new Date().toISOString() }
              : p
          )
        );
        setActiveProject((prev) => ({
          ...prev,
          reports: [newReport, ...prev.reports],
        }));
      } else {
        alert(`Research execution error: ${data.error || "Unknown error"}`);
      }
    } catch (error: any) {
      console.error("Failed to run research:", error);
      alert(`Error running research: ${error.message}`);
    } finally {
      setIsExecuting(false);
    }
  };

  // Upload document handler
  const handleFileUpload = async (file: File): Promise<UploadedDocInfo | null> => {
    try {
      return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onload = async (e) => {
          const base64Data = (e.target?.result as string)?.split(",")[1];
          if (!base64Data) {
            resolve(null);
            return;
          }

          const response = await fetch("/api/document/ingest", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              name: file.name,
              base64: base64Data,
              mimeType: file.type || "application/pdf",
            }),
          });

          const data = await response.json();
          if (data.success && data.document) {
            resolve(data.document);
          } else {
            resolve(null);
          }
        };
        reader.readAsDataURL(file);
      });
    } catch (err) {
      console.error("File upload error:", err);
      return null;
    }
  };

  // Create new project
  const handleCreateProject = () => {
    const name = prompt("Enter new Research Project Name:", "New Academic Inquiry");
    if (!name) return;

    const newProj: Project = {
      id: `proj-${Date.now()}`,
      name,
      description: "Academic research project workspace.",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      reports: [],
      bookmarks: [],
      uploadedFiles: [],
    };

    setProjects([newProj, ...projects]);
    setActiveProject(newProj);
    setActiveReport(null);
  };

  // Delete project
  const handleDeleteProject = (id: string) => {
    if (projects.length <= 1) return;
    const remaining = projects.filter((p) => p.id !== id);
    setProjects(remaining);
    if (activeProject.id === id) {
      setActiveProject(remaining[0]);
      setActiveReport(remaining[0].reports[0] || null);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-sans antialiased selection:bg-indigo-600 selection:text-white">
      {/* Header */}
      <Header
        activeProject={activeProject}
        projects={projects}
        onSelectProject={(p) => {
          setActiveProject(p);
          setActiveReport(p.reports[0] || null);
        }}
        onCreateProject={handleCreateProject}
        onToggleSidebar={() => setIsSidebarOpen(true)}
      />

      {/* Sidebar Drawer */}
      <Sidebar
        isOpen={isSidebarOpen}
        onClose={() => setIsSidebarOpen(false)}
        projects={projects}
        activeProject={activeProject}
        onSelectProject={(p) => {
          setActiveProject(p);
          setActiveReport(p.reports[0] || null);
          setIsSidebarOpen(false);
        }}
        onSelectReport={(r) => {
          setActiveReport(r);
          setIsSidebarOpen(false);
        }}
        onCreateProject={handleCreateProject}
        onDeleteProject={handleDeleteProject}
      />

      {/* Main Content Area */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 space-y-5">
        {/* Input & Search Section */}
        <ResearchInput
          onSearch={handleRunResearch}
          isExecuting={isExecuting}
          onFileUpload={handleFileUpload}
        />

        {/* 11-Layer Visualizer */}
        {(isExecuting || currentLayer > 0) && (
          <AgentPipelineVisualizer
            currentLayer={currentLayer}
            isExecuting={isExecuting}
          />
        )}

        {/* Active Research Report or Empty Welcome */}
        {activeReport ? (
          <ReportViewer report={activeReport} />
        ) : (
          <div className="bg-white border border-slate-200 rounded-2xl p-12 text-center my-8 shadow-sm">
            <div className="w-16 h-16 rounded-2xl bg-indigo-50 border border-indigo-100 text-indigo-600 flex items-center justify-center mx-auto mb-4 shadow-sm">
              <Cpu className="w-8 h-8" />
            </div>
            <h3 className="text-lg font-bold text-slate-900 mb-2">
              Ready to execute multi-agent research
            </h3>
            <p className="text-xs text-slate-500 max-w-md mx-auto leading-relaxed">
              Enter an academic query above or attach documents (PDF, DOCX, PPTX, Images) to run SoftRoy AI's 11-layer research pipeline.
            </p>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-4 text-center text-xs text-slate-500">
        <span>SoftRoy AI — Multi-Agent Academic Research Engine • Powered by Gemini 3.6 Flash & Academic APIs</span>
      </footer>
    </div>
  );
}
